using System.Collections.Generic;
using static UnityEngine.RemoteConfigSettingsHelper;

namespace API_For_TCG_Card_Shop_Simulator.Helpers
{
    public static class EnumListScript
    {
        // Base Game Rarities
        public static List<string> Rarities = new()
        {
            "Common",
            "Rare",
            "Epic",
            "Legendary",
            "SuperLegend"
        };

        // Base Game Elements
        public static List<string> Elements = new()
        {
            "Fire",
            "Earth",
            "Water",
            "Wind",
            "Destiny",
            "Champion",
            "GhostWhite",
            "GhostBlack",
            "Megabot",
            "FantasyRPG",
            "CatJob",
            "FoodieGO",
            "FoodieGOBW",
            "FoodieGOJP"
        };

        // Base Game Roles
        public static List<string> Roles = new()
        {
            "PhysicalAttacker",
            "Defender",
            "Support",
            "Healer",
            "MagicalAttacker",
            "AllRounder",
            "Disruptor"
        };

        // Base Game Skills
        public static List<string> Skills = new()
        {
            "DoNothing",
            "Charging",
            "None",
            "FireClaw",
            "BlazingClaw",
            "InfernoClaw",
            "HellfireClaw",
            "FlamePillar",
            "BlazingPillar",
            "InfernoPillar",
            "SunPillar",
            "SpitFire",
            "Fireball",
            "MegaFlare",
            "CometStrike",
            "PiercingHit",
            "PiercingStrike",
            "PiercingCrash",
            "OmegaPierce",
            "BlitzAttack",
            "BlitzStrike",
            "BlitzSmash",
            "BlitzCrash",
            "FireWall",
            "InfernoWall",
            "BlazingWall",
            "HellfireWall",
            "PsychUp",
            "CriticalWound",
            "DesperadoHit",
            "SolarFlare",
            "Counter",
            "FrenzyHit",
            "Charge",
            "SuperCharge",
            "MegaCharge",
            "GigaCharge",
            "StoneWall",
            "RockWall",
            "GiantWall",
            "GigaWall",
            "Grow",
            "SuperGrow",
            "MegaGrow",
            "GigaGrow",
            "PebbleBlast",
            "StoneBlast",
            "RockSmash",
            "BoulderCrush",
            "Cover",
            "Protection",
            "Safeguard",
            "PerfectGuard",
            "HardenShell",
            "FortifyShell",
            "PowerUp",
            "Sharpen",
            "FuryStrike",
            "SwipeAttack",
            "Earthquake",
            "AncientProtection",
            "HealingMist",
            "HealingShower",
            "HealingRain",
            "HealingWaterfall",
            "EnergyPool",
            "EnergyFountain",
            "EnergyRain",
            "EnergyFlood",
            "DrainHit",
            "DrainStrike",
            "DrainSmash",
            "DrainCrush",
            "ColdShot",
            "IceBurst",
            "IcicleBlast",
            "SubzeroBeam",
            "RegenPool",
            "RegenFountain",
            "RegenRain",
            "RegenFlood",
            "Osmosis",
            "CleansingMist",
            "IcicleField",
            "MassAbsorb",
            "Consume",
            "Rejuvenate",
            "PoisonFang",
            "VenomFang",
            "ToxicFang",
            "AcidFang",
            "PoisonBlast",
            "VenomBlast",
            "ToxicBlast",
            "AcidBlast",
            "SandShot",
            "SandBlast",
            "SandStorm",
            "SandHurricane",
            "PowerDrip",
            "PowerLeak",
            "Discharge",
            "Meltdown",
            "AirShot",
            "AirCutter",
            "SonicBoom",
            "WindBlade",
            "Berserk",
            "FocusFire",
            "PoisonMist",
            "PoisonStorm",
            "BlindingSmog",
            "StickyGoo",
            "SpeedUp",
            "SpeedDown",
            "SleepShot",
            "SleepBlast",
            "SleepMist",
            "SleepStorm",
            "Tornado",
            "MassBerserk",
            "Tailwind",
            "BattleCry",
            "None",
            "ThunderClaw",
            "StormClaw",
            "LightningClaw",
            "TempestClaw",
            "ThunderPillar",
            "StormPillar",
            "LightningPillar",
            "TempestPillar",
            "ElectricShock",
            "LightningBolt",
            "ThunderStrike",
            "StormStrike",
            "TempestStrike",
            "ShockingHit",
            "BlindingFlash",
            "Frostbite",
            "IcicleSlash",
            "GlacialBlow",
            "ArcticBlast",
            "Hailstorm",
            "IceStorm",
            "SnowballFight",
            "FrostField",
            "BlizzardBlast",
            "DrenchingRain",
            "FloodSurge",
            "TidalWave",
            "SurgingTide",
            "WaveCrash",
            "TorrentStrike",
            "GaleForce",
            "Windstorm",
            "Cyclone",
            "Whirlwind",
            "Vortex",
            "Hurricane",
            "Twister",
            "SpinAttack",
            "ChargeAttack",
            "CounterStrike",
            "ReboundHit",
            "Shockwave",
            "PulseWave",
            "ForceField",
            "Barrier",
            "ShieldBash",
            "ReflectHit",
            "EnergyGuard",
            "AuraShield",
            "SpiritWall",
            "MysticVeil"
        };

        // Base Game EObjectType
        public static Dictionary<string, int> ObjectTypes = new()
        {
            { "CashCounter", 0 },
            { "Trashbin", 1 },
            { "PersonalStash", 2 },
            { "PackageBoxBig", 3 },
            { "PackageBoxSmall", 4 },
            { "PackageBoxShelf", 5 },
            { "Shelf", 6 },
            { "ShelfSmall", 7 },
            { "WarehouseShelf", 8 },
            { "Card3d", 9 },
            { "CardShelf", 10 },
            { "PlayTable", 11 },
            { "ShelfSmallB", 12 },
            { "PersonalShelfA", 13 },
            { "PersonalShelfB", 14 },
            { "PersonalShelfC", 15 },
            { "FancyShelfA", 16 },
            { "FancyShelfB", 17 },
            { "HugeShelfA", 18 },
            { "HugeShelfB", 19 },
            { "CabinetA", 20 },
            { "LongShelfA", 21 },
            { "RusticShelfA", 22 },
            { "VintageCardTable", 23 },
            { "DisplayCardTableA", 24 },
            { "DisplayCardShelfA", 25 },
            { "DisplayCardShelfB", 26 },
            { "WarehouseShelfA", 27 },
            { "WarehouseShelfB", 28 },
            { "WarehouseShelfC", 29 },
            { "Workbench", 30 },
            { "AutoCleanser1", 31 },
            { "AutoCleanser2", 32 },
            { "AutoCleanser3", 33 },
        };

        // Base Game Actions
        public static Dictionary<string, int> GameActions = new()
        {
            { "Interact", 0 },
            { "Back", 1 },
            { "Cancel", 2 },
            { "PutItem", 3 },
            { "TakeItem", 4 },
            { "PutCard", 5 },
            { "TakeCard", 6 },
            { "TakeBox", 7 },
            { "OpenBox", 8 },
            { "CloseBox", 9 },
            { "OpenPhone", 10 },
            { "ClosePhone", 11 },
            { "Scroll", 12 },
            { "StartMoveObject", 13 },
            { "PlaceMoveObject", 14 },
            { "Throw", 15 },
            { "Rotate", 16 },
            { "OpenCardAlbum", 17 },
            { "CloseCardAlbum", 18 },
            { "TakeAlbumCard", 19 },
            { "FlipNextPage", 20 },
            { "FlipPreviousPage", 21 },
            { "FlipNextPage10", 22 },
            { "FlipPreviousPage10", 23 },
            { "GoNextDay", 24 },
            { "Jump", 25 },
            { "PauseGame", 26 },
            { "InitiateOpenPack", 27 },
            { "CancelOpenPack", 28 },
            { "OpenPack", 29 },
            { "BoxUpShelf", 30 },
            { "StartCounter", 31 },
            { "ExitCounter", 32 },
            { "ScanCounter", 33 },
            { "DoneCounter", 34 },
            { "SortAlbum", 35 },
            { "InteractLeft", 36 },
            { "InteractRight", 37 },
            { "TrashDispose", 38 },
            { "BackF", 39 },
            { "SetPrice", 40 },
            { "AddChange", 41 },
            { "RemoveChange", 42 },
            { "StoreBox", 43 },
            { "MoveForward", 44 },
            { "MoveBackward", 45 },
            { "MoveLeft", 46 },
            { "MoveRight", 47 },
            { "LookAround", 48 },
            { "InitiateSpray", 49 },
            { "CancelSpray", 50 },
            { "Spray", 51 },
            { "ManageEvent", 52 },
            { "Sprint", 53 },
            { "MoveForwardAlt", 54 },
            { "MoveBackwardAlt", 55 },
            { "MoveLeftAlt", 56 },
            { "MoveRightAlt", 57 },
            { "PlaceBox", 58 },
            { "MenuConfirm", 59 },
            { "MenuBack", 60 },
            { "RotateB", 61 },
            { "RemoveLabel", 62 },
            { "Refill", 63 },
            { "TurnOn", 64 },
            { "TurnOff", 65 },
            { "OpenCardBox", 66 },
            { "ViewAlbumCard", 67 },
            { "SellBoxedUpShelf", 68 }
        };

        // Base Game GameEventFormat
        public static Dictionary<string, int> GameEventFormat = new()
        {
            { "Standard", 1 },
            { "Pauper",2 },
            { "FireCup", 3 },
            { "EarthCup", 4 },
            { "WaterCup", 5 },
            { "WindCup", 6 },
            { "FirstEditionVintage", 7 },
            { "SilverBorder", 8 },
            { "GoldBorder", 9 },
            { "ExBorder", 10 },
            { "FullArtBorder", 11 },
            { "Foil", 12 }
        };

        // Base Game Item Type
        public static Dictionary<string, int> ItemType = new()
        {
            { "BasicCardPack", 0 },
            { "BasicCardBox",1 },
            { "RareCardPack", 2 },
            { "RareCardBox", 3 },
            { "EpicCardPack", 4 },
            { "EpicCardBox", 5 },
            { "LegendaryCardPack", 6 },
            { "LegendaryCardBox", 7 },
            { "DestinyBasicCardPack", 8 },
            { "DestinyBasicCardBox", 9 },
            { "DestinyRareCardPack",10 },
            { "DestinyRareCardBox",11 },
            { "DestinyEpicCardPack",12 },
            { "DestinyEpicCardBox",13 },
            { "DestinyLegendaryCardPack",14 },
            { "DestinyLegendaryCardBox",15 },
            { "GhostPack",16 },
            { "MegabotPack",17 },
            { "FantasyRPGPack",18 },
            { "CatJobPack",19 },
            { "FoodieGOPack",20 },
            { "FoodieGOBWPack",21 },
            { "FoodieGOJPPack",22 },
            { "Deodorant",23 },
            { "DeckBox1",24 },
            { "DeckBox2",25 },
            { "DeckBox3", 26 },
            { "DeckBox4",27 },
            { "BinderBook",28 },
            { "D20DiceBox",29 },
            { "D20DiceBox2",30 },
            { "D20DiceBox3",31 },
            { "D20DiceBox4",32 },
            { "Toy_PiggyA",33 },
            { "Toy_GolemA",34 },
            { "Toy_StarfishA",35 },
            { "Toy_BatA",36 },
            { "BulkBox_TetramonBase",37 },
            { "BulkBox_TetramonDestiny",38 },
            { "Toy_PiggyB",39 },
            { "Toy_PiggyC",40 },
            { "Toy_PiggyD",41 },
            { "Toy_GolemB",42 },
            { "Toy_GolemC",43 },
            { "Toy_GolemD",44 },
            { "Toy_StarfishB",45 },
            { "Toy_StarfishC",47 },
            { "Toy_StarfishD",48 },
            { "Toy_BatB",49 },
            { "Toy_BatC",50 },
            { "Toy_BatD",51 },
            { "Toy_Beetle",52 },
            { "Toy_FoxB",53 },
            { "Toy_ToonZ",54 },
            { "BinderBookPremium",55 },
            { "PreconDeck_Fire",56 },
            { "PreconDeck_Earth",57 },
            { "PreconDeck_Water",58 },
            { "PreconDeck_Wind",59 },
            { "PreconDeck_FireDestiny",60 },
            { "PreconDeck_EarthDestiny",61 },
            { "PreconDeck_WaterDestiny",62 },
            { "PreconDeck_WindDestiny",63 },
            { "CardSleeve_Clear",64 },
            { "CardSleeve_Tetramon",65 },
            { "CardSleeve_Fire",66 },
            { "CardSleeve_Earth",67 },
            { "CardSleeve_Water",68 },
            { "CardSleeve_Wind",69 },
            { "Playmat1",70 },
            { "Playmat2",71 },
            { "Playmat2b",72 },
            { "Playmat3",73 },
            { "Playmat4",74 },
            { "Playmat5",75 },
            { "Playmat6",76 },
            { "Playmat7",76 },
            { "Playmat8",77 },
            { "Playmat9",78 },
            { "Playmat10",79 },
            { "Playmat11",80 },
            { "Playmat12",81 },
            { "Playmat13",82 },
            { "Playmat14",83 },
            { "Boardgame_Speedrobo_Necro",84 },
            { "Boardgame_Speedrobo_Claim",85 },
            { "Boardgame_Speedrobo_Mafia",86 },
            { "Boardgame_Speedrobo_SystemGate1",87 },
            { "Boardgame_Speedrobo_SystemGate2",88 },
            { "BulkBox_TetramonBaseGradeHG",89 },
            { "BulkBox_TetramonBaseGradeMG",90 },
            { "BulkBox_TetramonBaseGradePG",91 },
            { "BulkBox_TetramonDestinyGradeHG",92 },
            { "BulkBox_TetramonDestinyGradeMG",93 },
            { "BulkBox_TetramonDestinyGradePG",94 },
            { "Manga1",95 },
            { "Manga2",96 },
            { "Manga3",97 },
            { "Manga4",98 },
            { "Manga5",99 },
            { "Manga6",100 },
            { "Manga7",101 },
            { "Manga8",102 },
            { "Manga9",103 },
            { "Manga10",104 },
            { "Manga11",105 },
            { "Manga12",106 },
            { "Manga13",107 },
            { "Manga14",108 },
            { "PlayMat15",109 },
            { "PlayMat16",110 },
            { "PlayMat17",111 },
            { "PlayMat18",112 },
        };

        // Base ECollectionPackType
        public static Dictionary<string, int> CollectionPackType = new()
        {
            { "BasicCardPack", 0 },
            { "RareCardPack", 1 },
            { "EpicCardPack", 2 },
            { "LegendaryCardPack",3 },
            { "DestinyBasicCardPack",4 },
            { "DestinyRareCardPack",5 },
            { "DestinyEpicCardPack",6 },
            { "DestinyLegendaryCardPack",7 },
            { "GhostPack",8 },
            { "MegabotPack",9 },
            { "FantasyRPGPack",10 },
            { "CatJobPack",11 },
            { "FoodieGOPack",12 },
            { "FoodieGOBWPack",13 },
            { "FoodieGOJPPack",14 }
        };

        // Base Game EPriceChangeType
        public static Dictionary<string, int> PriceChangeType = new()
        {
            { "CommonPackCard", 0 },
            { "RarePackCard",1 },
            { "EpicPackCard",2 },
            { "LegendPackCard",3 },
            { "NoneCommonPackCard",4 },
            { "RandomRarityPackCard",5 },
            { "FireElement",6 },
            { "EarthElement",7 },
            { "WaterElement",8 },
            { "WindElement",9 },
            { "RandomElement",10 },
            { "FirstEdition",11 },
            { "SilverBorder",12 },
            { "GoldBorder",13 },
            { "ExBorder",14 },
            { "FullArtBorder",15 },
            { "RandomBorder",16 },
            { "Foil",17 },
            { "NonFoil",18 },
            { "RandomEffect",19 },
            { "Figurine",20 },
            { "ExpansionTetramon",21 }
        };

        // Base Game EItemCategory
        public static Dictionary<string, int> ItemCategory = new()
        {
            { "TCG",0 },
            { "Deckbox",1 },
            { "Dice",2 },
            { "Sleeve",3 },
            { "Manga",4 },
            { "Playmat",5 },
            { "Figurine",6 },
            { "Boardgame",7 }
        };
        // Base Game EQuestType
        public static Dictionary<string, int> QuestType = new()
        {
            { "MainCounterLevel",1 },
            { "TetramonCardCollected",2 },
            { "UnlockTetramonBasicBox",3 },
            { "UnlockTetramonLegendPack",4 },
            { "SellTetramonBasicPack",5 },
            { "SellTetramonRareBox",6 },
            { "SellTetramonEpicPack",7 },
            { "SellTetramonLegendBox",8 },
            { "CustomerVisit",9 },
            { "EarnGlobalShopPoint",10 },
            { "UnlockMediumShelf",11 },
            { "UnlockLargeShelf",12 },
            { "UnlockGiantShelf",13 },
            { "UnlockPiggyAStatue",14 },
            { "UnlockPiggyBStatue",15 },
            { "UnlockPiggyCStatue",16 },
            { "UnlockPiggyDStatue",17 },
            { "UpgradeSmallShelf",18 },
            { "UpgradeSmallTable",19 },
            { "UpgradeMediumTable",20 },
            { "UpgradeLongTable",21 },
            { "UpgradeATMLevel",22 },
            { "UpgradeLoudspeakerLevel",23 },
            { "UpgradeTrolleyLevel",24 },
            { "UpgradePackStorageLevel",25 },
            { "UpgradePigniStatueLevel",26 },
            { "UpgradeTrickstarStatueLevel",27 },
            { "UpgradeMeganiteStatueLevel",28 },
            { "UpgradeDracunixStatueLevel",29 },
            { "UnlockVehicleVan",30 },
            { "UnlockVehicleTruck",31 },
            { "UnlockVehicleTrailer",32 },
            { "UpgradeBike",32 },
            { "UpgradeVan",33 },
            { "UpgradeHelicopter",34 },
            { "DestinyCardCollected",35 },
            { "SellDestinyBasicPack",36 },
            { "SellDestinyRarePack",37 },
            { "SellDestinyEpicPack",38 },
            { "SellDestinyLegendPack",39 },
            { "GhostCardCollected",40 },
            { "SellGhostPack",41 }
        };

        // Base Game ECustomerReviewType
        public static Dictionary<string, int> CustomerReviewType = new()
        {
            { "StoreGeneric",0 },
            { "ItemVariety",1 },
            { "ItemPrice",2 },
            { "CardPrice",3 },
            { "CardRarity",4 },
            { "PlaytablePrice",5 },
            { "SmellyCustomer",6 },
            { "BlockedStore",7 },
            { "OwnerOpenPack",8 },
            { "GiveManyChangePennies",9 }
        };

        // New Enums Dict
        public static Dictionary<string, int> TetramonEnums = new()
        {
            { "Pigni", 1 },
            { "Burpig", 2 },
            { "Inferhog", 3 },
            { "Blazoar", 4 },
            { "Kidsune", 5 },
            { "Bonfiox", 6 },
            { "Honobi", 7 },
            { "Kyuenbi", 8 },
            { "Nanomite", 9 },
            { "Decimite", 10 },
            { "Meganite", 11 },
            { "Giganite", 12 },
            { "Sapoling", 13 },
            { "Forush", 14 },
            { "Timbro", 15 },
            { "Mammotree", 16 },
            { "Minstar", 17 },
            { "Trickstar", 18 },
            { "Princestar", 19 },
            { "Kingstar", 20 },
            { "Shellow", 21 },
            { "Clamigo", 22 },
            { "Aquariff", 23 },
            { "Fistronk", 24 },
            { "Wurmgle", 25 },
            { "Pupazz", 26 },
            { "Mothini", 27 },
            { "Royalama", 28 },
            { "Nocti", 29 },
            { "Lunight", 30 },
            { "Vampicant", 31 },
            { "Dracunix", 32 },
            { "Minotos", 33 },
            { "Drilceros", 34 },
            { "Grizzaw", 35 },
            { "Jelicleen", 36 },
            { "Wispo", 37 },
            { "Mummog", 38 },
            { "Helio", 39 },
            { "Pixy", 40 },
            { "Flory", 41 },
            { "Magnoria", 42 },
            { "Werboo", 43 },
            { "Flami", 44 },
            { "Angez", 45 },
            { "Moskit", 46 },
            { "Kyrone", 47 },
            { "Twofrost", 48 },
            { "Threeze", 49 },
            { "Hydroid", 50 },
            { "Drakon", 51 },
            { "Bogon", 52 },
            { "Hydron", 53 },
            { "Raizon", 54 },
            { "Tortugor", 55 },
            { "Lupup", 56 },
            { "Luphire", 57 },
            { "Lucinder", 58 },
            { "Lucadence", 59 },
            { "Gupi", 60 },
            { "Sharfin", 61 },
            { "Gilgabass", 62 },
            { "Jigajawr", 63 },
            { "Batrang", 64 },
            { "Dusko", 65 },
            { "Wolgin", 66 },
            { "Jacktern", 67 },
            { "Tetron", 68 },
            { "Raxx", 69 },
            { "Gannon", 70 },
            { "GigatronX", 71 },
            { "Clawop", 72 },
            { "Clawdos", 73 },
            { "Clawaken", 74 },
            { "Clawcifear", 75 },
            { "Sunflork", 76 },
            { "Scarlios", 77 },
            { "Scarkgorus", 78 },
            { "Crobib", 79 },
            { "Crosilisk", 80 },
            { "Crorathian", 81 },
            { "Nimblis", 82 },
            { "Nimboculo", 83 },
            { "Nimbustrike", 84 },
            { "Esmeri", 85 },
            { "Esmerock", 86 },
            { "Esmerdios", 87 },
            { "Litspire", 88 },
            { "Voltrex", 89 },
            { "Crablox", 90 },
            { "Clawvenger", 91 },
            { "Flambrolly", 92 },
            { "Lumie", 93 },
            { "Seedant", 94 },
            { "Budwing", 95 },
            { "Buzzeed", 96 },
            { "Beakai", 97 },
            { "Talontsu", 98 },
            { "Talonika", 99 },
            { "Talonryu", 100 },
            { "Kataryu", 101 },
            { "Katengu", 102 },
            { "Mufflin", 103 },
            { "Muffleur", 104 },
            { "Mufflimax", 105 },
            { "Anguifish", 106 },
            { "Amneshark", 107 },
            { "Amnesilla", 108 },
            { "Frizard", 109 },
            { "Gekoflare", 110 },
            { "Terradrakon", 111 },
            { "Flamchik", 112 },
            { "Pyropeck", 113 },
            { "Poseia", 114 },
            { "Posteed", 115 },
            { "Poseigon", 116 },
            { "Poseidrake", 117 },
            { "Sludglop", 118 },
            { "Sludgetox", 119 },
            { "Toxigoop", 120 },
            { "Toximuck", 121 }
        };

        public static Dictionary<string, int> MegabotEnums = new()
        {
            { "Alpha", 1 },
            { "Beta", 2 },
            { "Gamma", 3 },
            { "Ronin", 4 },
            { "Bumblebee", 5 },
            { "Orca", 6 },
            { "Garuda", 7 },
            { "Viper", 8 },
            { "Blitz", 9 },
            { "Cyclops", 10 },
            { "Kabuto", 11 },
            { "Minotaur", 12 },
            { "Spectre", 13 },
            { "Wolf", 14 },
            { "Bolt", 15 },
            { "Hawk", 16 },
            { "Cyber", 17 },
            { "Space", 18 },
            { "Hanger", 19 },
            { "Arena", 20 },
            { "UndergroundDark", 21 },
            { "UndergroundLight", 22 },
            { "RoninBoss", 23 },
            { "OrcaBoss", 24 },
            { "GarudaBoss", 25 },
            { "ViperBoss", 26 },
            { "Max", 27 },
            { "Shockwave", 28 },
            { "Tremor", 29 },
            { "Rhino", 30 },
            { "RoninArt", 31 },
            { "GarudaArt", 32 },
            { "MaxArt", 33 },
            { "MinotaurArt", 34 },
            { "WolfArt", 35 },
            { "SkullArt", 36 },
            { "OrcaAlt", 37 },
            { "GarudaAlt", 38 },
            { "ViperAlt", 39 },
            { "KabutoAlt", 40 },
            { "Neon", 41 },
            { "Pulse", 42 },
            { "Raptor", 43 },
            { "AncientHammer", 44 },
            { "ArcMissile", 45 },
            { "Axe", 46 },
            { "BarrageMisile", 47 },
            { "BarrelHammer", 48 },
            { "BattleChip", 49 },
            { "BoxingGlove", 50 },
            { "ChainGun", 51 },
            { "ChillMissile", 52 },
            { "ColdShoulder", 53 },
            { "CresentClaw", 54 },
            { "CresentMachete", 55 },
            { "CrimsonWheel", 56 },
            { "CryoBlaster", 57 },
            { "Drill", 58 },
            { "DualMissile", 59 },
            { "ElectricBroadSword", 60 },
            { "ElectricChainsaw", 61 },
            { "ElectricSpike", 62 },
            { "EnergyShield", 63 },
            { "FanBlade", 64 },
            { "FeatherBlade", 65 },
            { "FireAxe", 66 },
            { "FireBroadsword", 67 },
            { "FireKatana", 68 },
            { "FireRocket", 69 },
            { "FireShield", 70 },
            { "FireTwinAxe", 71 },
            { "Flamethrower", 72 },
            { "FreezeBomb", 73 },
            { "GigaBlade", 74 },
            { "GigaCommon", 75 },
            { "GreatCleaver", 76 },
            { "HeatKnife", 77 },
            { "HeatMissile", 78 },
            { "IceBroadsword", 79 },
            { "IceMortar", 80 },
            { "IcePike", 81 },
            { "IceSpinner", 82 },
            { "IceTwinSpear", 83 },
            { "InfernoBoost", 84 },
            { "IronBall", 85 },
            { "JetBurner", 86 },
            { "Katana", 87 },
            { "KnightShield", 88 },
            { "KnightSword", 89 },
            { "LightSaber", 90 },
            { "LionShield", 91 },
            { "MagneticCoil", 92 },
            { "MaulerMace", 93 },
            { "MegaVoltBeam", 94 },
            { "MiniMissile", 95 },
            { "MissileCannon", 96 },
            { "MoonlightBlade", 97 },
            { "MorningStar", 98 },
            { "Mortar", 99 },
            { "PulseCannon", 100 },
            { "RailCannon", 101 },
            { "Ravager", 102 },
            { "RocketMissile", 103 },
            { "RollerSpike", 104 },
            { "ShurikenBlade", 105 },
            { "SonicBlaster", 106 },
            { "SpikeBall", 107 },
            { "SpikedWarhammer", 108 },
            { "Sword", 109 },
            { "ThorHammer", 110 },
            { "Thunderblade", 111 },
            { "ThunderTwinBlade", 112 },
            { "Windblaster", 113 }
        };

        public static Dictionary<string, int> FantasyRPGEnums = new()
        {
            { "Archer", 1 },
            { "ArmoredSlime", 2 },
            { "AxeWarrior", 3 },
            { "Basilisk", 4 },
            { "Blacksmith", 5 },
            { "CatMage", 6 },
            { "CatPirate", 7 },
            { "CatTheif", 8 },
            { "Cook", 9 },
            { "DarkKnight", 10 },
            { "Dragon", 11 },
            { "DragonKnight", 12 },
            { "EldritchCreature", 13 },
            { "Farmer", 14 },
            { "Fencer", 15 },
            { "Florist", 16 },
            { "GoblinMage", 17 },
            { "GoblinTheif", 18 },
            { "GoblinWarrior", 19 },
            { "Golem", 20 },
            { "Grandma", 21 },
            { "Harpy1", 22 },
            { "Harpy2", 23 },
            { "InkKnight", 24 },
            { "Jester1", 25 },
            { "Jester2", 26 },
            { "King", 27 },
            { "Knight", 28 },
            { "Lamia", 29 },
            { "Mage", 30 },
            { "Mimic1", 31 },
            { "Mimic2", 32 },
            { "MushroomMonster", 33 },
            { "Noble1", 34 },
            { "Noble2", 35 },
            { "Peasent1", 36 },
            { "Peasent2", 37 },
            { "Pheonix", 38 },
            { "Queen", 39 },
            { "Reaper", 40 },
            { "Schoolboy1", 41 },
            { "Schoolboy2", 42 },
            { "Slime", 43 },
            { "Snake", 44 },
            { "Traveler", 45 },
            { "TreeMonster", 46 },
            { "Vampire", 47 },
            { "Witch", 48 },
            { "Wizard", 49 },
            { "Wolf", 50 }
        };

        public static Dictionary<string, int> CatJobEnums = new()
        {
            { "Teacher", 1 },
            { "Detective", 2 },
            { "Woodworker", 3 },
            { "Plumber", 4 },
            { "Electrician", 5 },
            { "Soldier", 6 },
            { "General", 7 },
            { "Police", 8 },
            { "Firemen", 9 },
            { "Farmer", 10 },
            { "Architect", 11 },
            { "Construction", 12 },
            { "BodyBuilder", 13 },
            { "Archer", 14 },
            { "Explorer", 15 },
            { "Hiker", 16 },
            { "Programmer", 17 },
            { "Laundry", 18 },
            { "Libarian", 19 },
            { "Racer", 20 },
            { "Florist", 21 },
            { "Geologist", 22 },
            { "Gamer", 23 },
            { "Maid", 24 },
            { "Barber", 25 },
            { "Bartender", 26 },
            { "Bouncer", 27 },
            { "Composer", 28 },
            { "Director", 29 },
            { "Investor", 30 },
            { "Singer", 31 },
            { "Musician", 32 },
            { "Artist", 33 },
            { "Photographer", 34 },
            { "Janitor", 35 },
            { "Lawyer", 36 },
            { "Phychic", 37 },
            { "Astronaut", 38 },
            { "Pirate", 39 },
            { "Scout", 40 }
        };

        public static Dictionary<string, Dictionary<string, int>> SetDict = new()
        {
            { "Tetramon", TetramonEnums },
            { "Megabot", MegabotEnums },
            { "FantasyRPG", FantasyRPGEnums },
            { "CatJob", CatJobEnums }
        };

        public static Dictionary<string, int> MonsterMax = new()
        {
            { "Tetramon", 122 },
            { "Magabot", 113 },
            { "FantasyRPG", 50 },
            { "CatJob", 40 }
        };
    }
}