using API_For_TCG_Card_Shop_Simulator.Helpers.APIObj_s;
using System;
using System.Collections.Generic;

namespace API_For_TCG_Card_Shop_Simulator.Helpers.ENUM_CONVERSIONS
{
	public class MonsterType
	{
		public enum EMonsterTypeLocal
		{
			None = 0,
			PiggyA = 1,
			PiggyB = 2,
			PiggyC = 3,
			PiggyD = 4,
			FoxA = 5,
			FoxB = 6,
			FoxC = 7,
			FoxD = 8,
			GolemA = 9,
			GolemB = 10,
			GolemC = 11,
			GolemD = 12,
			TreeA = 13,
			TreeB = 14,
			TreeC = 15,
			TreeD = 16,
			StarfishA = 17,
			StarfishB = 18,
			StarfishC = 19,
			StarfishD = 20,
			ShellyA = 21,
			ShellyB = 22,
			ShellyC = 23,
			ShellyD = 24,
			BugA = 25,
			BugB = 26,
			BugC = 27,
			BugD = 28,
			BatA = 29,
			BatB = 30,
			BatC = 31,
			BatD = 32,
			Skull = 33,
			Beetle = 34,
			Bear = 35,
			Jellyfish = 36,
			Wisp = 37,
			MummyMan = 38,
			FlowerA = 39,
			FlowerB = 40,
			FlowerC = 41,
			FlowerD = 42,
			WeirdBirdA = 43,
			FireSpirit = 44,
			Angez = 45,
			Mosquito = 46,
			HydraA = 47,
			HydraB = 48,
			HydraC = 49,
			HydraD = 50,
			DragonFire = 51,
			DragonEarth = 52,
			DragonWater = 53,
			DragonThunder = 54,
			Turtle = 55,
			FireWolfA = 56,
			FireWolfB = 57,
			FireWolfC = 58,
			FireWolfD = 59,
			FishA = 60,
			FishB = 61,
			FishC = 62,
			FishD = 63,
			HalloweenA = 64,
			HalloweenB = 65,
			HalloweenC = 66,
			HalloweenD = 67,
			TronA = 68,
			TronB = 69,
			TronC = 70,
			TronD = 71,
			LobsterA = 72,
			LobsterB = 73,
			LobsterC = 74,
			LobsterD = 75,
			FireBirdA = 76,
			FireBirdB = 77,
			FireBirdC = 78,
			SerpentA = 79,
			SerpentB = 80,
			SerpentC = 81,
			CloudA = 82,
			CloudB = 83,
			CloudC = 84,
			EmeraldA = 85,
			EmeraldB = 86,
			EmeraldC = 87,
			Crystalmon = 88,
			ElecDragon = 89,
			CrabA = 90,
			CrabB = 91,
			FireUmbrellaDragon = 92,
			Lanternmon = 93,
			SeedBugA = 94,
			SeedBugB = 95,
			SeedBugC = 96,
			NinjaBirdA = 97,
			NinjaBirdB = 98,
			NinjaBirdC = 99,
			NinjaBirdD = 100,
			NinjaCrowC = 101,
			NinjaCrowD = 102,
			MuffinTreeA = 103,
			MuffinTreeB = 104,
			MuffinTreeC = 105,
			SharkFishA = 106,
			SharkFishB = 107,
			SharkFishC = 108,
			FireGeckoA = 109,
			FireGeckoB = 110,
			EarthDino = 111,
			FireChickenA = 112,
			FireChickenB = 113,
			SeahorseA = 114,
			SeahorseB = 115,
			SeahorseC = 116,
			SeahorseD = 117,
			SlimeA = 118,
			SlimeB = 119,
			SlimeC = 120,
			SlimeD = 121,
		}

		public enum EMegaBotType
		{ 
			None = 0,
			Alpha = 1,
			Beta = 2,
			Gamma = 3,
			Ronin = 4,
			Bumblebee = 5,
			Orca = 6,
			Garuda = 7,
			Viper = 8,
			Blitz = 9,
			Cylops = 10,
			Kabuto = 11,
			Minotaur = 12,
			Spectre = 13,
			Wolf = 14,
			Bolt = 15,
			Hawk = 16,
			Cyber = 17,
			Space = 18,
			Hangar = 19,
			Arena = 20,
			UndergroundDark = 21,
			UndergroundLight = 22,
			RoninBoss = 23,
			OrcaBoss = 24,
			GarudaBoss = 25,
			ViperBoss = 26,
			Max = 27,
			Shockwave = 28,
			Tremor = 29,
			Rhino = 30,
			RoninArt = 31,
			GarudaArt = 32,
			MaxArt = 33,
			MinotaurArt = 34,
			WolfArt = 35,
			SkullArt = 36,
			OrcaAlt = 37,
			GarudaAlt = 38,
			ViperAlt = 39,
			KabutoAlt = 40,
			Neon = 41,
			Pulse = 42,
			Raptor = 43,
			AncientHammer = 44,
			ArcMissile = 45,
			Axe = 46,
			BarrageMissle = 47,
			BarrelHammer = 48,
			BattleChip = 49,
			BoxingGlove = 50,
			ChainGun = 51,
			ChillMissile = 52,
			ColdShoulder = 53,
			CrescentClaw = 54,
			CrescentMachete = 55,
			CrimsonWheel = 56,
			CryoBlaster = 57,
			Drill = 58,
			DualMissile = 59,
			ElecBroadsword = 60,
			ElectricChainsaw = 61,
			ElectricSpike = 62,
			EnergyShield = 63,
			FanBlade = 64,
			FeatherBlade = 65,
			FireAxe = 66,
			FireBroadsword = 67,
			FireKatana = 68,
			FireRocket = 69,
			FireShield = 70,
			FireTwinAxe = 71,
			Flamethrower = 72,
			FreezeBomb = 73,
			GigaBlade = 74,
			GigaCannon = 75,
			GreatCleaver = 76,
			HeatKnife = 77,
			HeatMissile = 78,
			IceBroadsword = 79,
			IceMortar = 80,
			IcePike = 81,
			IceSpinner = 82,
			IceTwinSpear = 83,
			InfernoBoost = 84,
			IronBall = 85,
			JetBurner = 86,
			Katana = 87,
			KnightShield = 88,
			KnightSword = 89,
			LightSaber = 90,
			LionShield = 91,
			MagneticCoil = 92,
			MaulerMace = 93,
			MegavoltBeam = 94,
			MiniMissile = 95,
			MissileCannon = 96,
			MoonlightBlade = 97,
			MorningStar = 98,
			Mortar = 99,
			PulseCannon = 100,
			RailCannon = 101,
			Ravager = 102,
			RocketMissile = 103,
			RollerSpike = 104,
			ShurikenBlade = 105,
			SonicBlaster = 106,
			SpikeBall = 107,
			SpikedWarhammer = 108,
			Sword = 109,
			ThorHammer = 110,
			Thunderblade = 111,
			ThunderTwinBlade = 112,
			WingBooster = 113,
		}

		public enum EFantasyRPGType
		{
			None = 0,
			Archer = 1,
			ArmoredSlime = 2,
			AxeWarrior = 3,
			Basilisk = 4,
			Blacksmith = 5,
			CatMage = 6,
			CatPirate1 = 7,
			CatThief = 8,
			Cook = 9,
			DarkKnight = 10,
			Dragon = 11,
			DragonKnight = 12,
			EldritchCreature = 13,
			Farmer = 14,
			Fencer = 15,
			Florist = 16,
			GoblinMage = 17,
			GoblinThief = 18,
			GoblinWarrior = 19,
			Golem = 20,
			Grandma = 21,
			Harpy1 = 22,
			Harpy2 = 23,
			InkKnight = 24,
			Jester1 = 25,
			Jester2 = 26,
			King = 27,
			Knight = 28,
			Lamia = 29,
			Mage = 30,
			Mimic1 = 31,
			Mimic2 = 32,
			MushroomMonster = 33,
			Noble1 = 34,
			Noble2 = 35,
			Peasant1 = 36,
			Peasant2 = 37,
			Phoenix = 38,
			Queen = 39,
			Reaper = 40,
			Schoolboy1 = 41,
			SchoolBoy2 = 42,
			Slime = 43,
			Snake = 44,
			Traveller = 45,
			TreeMonster = 46,
			Vampire = 47,
			Witch = 48,
			Wizard = 49,
			WolfFantasy = 50,
		}

		public enum ECatJobType
		{
			None = 0,
			Teacher = 1,
			Detective = 2,
			Woodworker = 3,
			Plumber = 4,
			Electrician = 5,
			Soldier = 6,
			General = 7,
			Police = 8,
			Fireman = 9,
			Farmer = 10,
			Architect = 11,
			Construction = 12,
			Bodybuilder = 13,
			Archer = 14,
			Explorer = 15,
			Hiker = 16,
			Programmer = 17,
			Librarian = 18,
			Laundry = 19,
			Racer = 20,
			Florist = 21,
			Geologist = 22,
			Gamer = 23,
			Maid = 24,
			Barber = 25,
			Bartender = 26,
			Bouncer = 27,
			Composer = 28,
			Director = 29,
			Investor = 30,
			Singer = 31,
			Musician = 32,
			Artist = 33,
			Photographer = 34,
			Lawyer = 35,
			Janitor = 36,
			Psychic = 37,
			Astronaut = 38,
			Scout = 39,
			Pirate = 40,
		}
		public static List<EMonsterTypeLocal> TetramonEnumList = new List<EMonsterTypeLocal>();
		public static List<EMegaBotType> MegaBotEnumList = new List<EMegaBotType>();
		public static List<EFantasyRPGType> FantasyRPGEnumList = new List<EFantasyRPGType>();
		public static List<ECatJobType> CatJobEnumList = new List<ECatJobType>();
		public static void CheckMonsterMaxes()
		{
			Console.WriteLine("Tetramon [BASE GAME] Max: " + (int)EMonsterType.MAX);
			foreach (var Name in Enum.GetValues(typeof(EMonsterTypeLocal)))
			{
				var newName = Enum.Parse<EMonsterTypeLocal>(Name.ToString(),true);
				TetramonEnumList.Add(newName);
			}
			Console.WriteLine("Megabot [BASE GAME] Max: " + (int)EMonsterType.MAX_MEGABOT);
			foreach (var Name in Enum.GetValues(typeof(EMegaBotType)))
			{
				var newName = Enum.Parse<EMegaBotType>(Name.ToString(),true);
				MegaBotEnumList.Add(newName);
			}
			Console.WriteLine("FantasyRPG [BASE GAME] Max: " + (int)EMonsterType.MAX_FANTASYRPG);
			foreach (var Name in Enum.GetValues(typeof(EFantasyRPGType)))
			{
				var newName = Enum.Parse<EFantasyRPGType>(Name.ToString(),true);
				FantasyRPGEnumList.Add(newName);
			}
			Console.WriteLine("CatJob [BASE GAME] Max: " + (int)EMonsterType.MAX_CATJOB);
			foreach (var Name in Enum.GetValues(typeof(ECatJobType)))
			{
				var newName = Enum.Parse<ECatJobType>(Name.ToString(),true);
				CatJobEnumList.Add(newName);
			}
			Console.WriteLine(CSingleton<InventoryBase>.Instance.m_MonsterData_SO);
		}
	}
}