<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	<TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>List_Definer_Prepatch</AssemblyName>
	<Description>Defines lists which will later be loaded by the following patcher and plugin.</Description>
    <Version>1.0.0</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <RootNamespace>List_Definer</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx-MonoMod_Loader_Inscryption" Version="1.0.0" />
    <PackageReference Include="BepInEx.Core" Version="5.4.21" />
    <PackageReference Include="BepInEx.PluginInfoProps" Version="2.1.0" />
    <PackageReference Include="UnityEngine.Modules" Version="2019.4.24" IncludeAssets="compile" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.5.0-beta.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <Reference Include="AnsiConsolePlugin">
      <HintPath>Lib\AnsiConsolePlugin.dll</HintPath>
      <Publicize>true</Publicize>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\TCG Card Shop Simulator\Card Shop Simulator_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Publicize>true</Publicize>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
