using JetBrains.Annotations;
using System.Collections.Generic;

namespace API_For_TCG_Card_Shop_Simulator.Scripts
{
    public static class EnumListScript
    { 
        
        public static List<string> Rarities = new List<string> {
            "Common",
            "Rare",
            "Epic",
            "Legendary",
            "SuperLegend"
        };
        public static List<string> Elements = new List<string> {
            "None",
            "Fire",
            "Earth",
            "Water",
            "Wind",
            "Destiny",
            "Champion",
            "GhostWhite",
            "GhostBlack",
            "Megabot",
            "FantasyRPG",
            "CatJob",
            "FoodieGO",
            "FoodieGOBW",
            "FoodieGOJP"
        };
        // Old Enums List
        public static List<string> CardsTotal = new List<string> {
            "None",
            "PiggyA",
            "PiggyB",
            "PiggyC",
            "PiggyD",
            "FoxA",
            "FoxB",
            "FoxC",
            "FoxD",
            "GolemA",
            "GolemB",
            "GolemC",
            "GolemD",
            "TreeA",
            "TreeB",
            "TreeC",
            "TreeD",
            "StarfishA",
            "StarfishB",
            "StarfishC",
            "StarfishD",
            "ShellyA",
            "ShellyB",
            "ShellyC",
            "ShellyD",
            "BugA",
            "BugB",
            "BugC",
            "BugD",
            "BatA",
            "BatB",
            "BatC",
            "BatD",
            "Skull",
            "Beetle",
            "Bear",
            "Jellyfish",
            "Wisp",
            "MummyMan",
            "FlowerA",
            "FlowerB",
            "FlowerC",
            "FlowerD",
            "WeirdBirdA",
            "FireSpirit",
            "Angez",
            "Mosquito",
            "HydraA",
            "HydraB",
            "HydraC",
            "HydraD",
            "DragonFire",
            "DragonEarth",
            "DragonWater",
            "DragonThunder",
            "Turtle",
            "FireWolfA",
            "FireWolfB",
            "FireWolfC",
            "FireWolfD",
            "FishA",
            "FishB",
            "FishC",
            "FishD",
            "HalloweenA",
            "HalloweenB",
            "HalloweenC",
            "HalloweenD",
            "TronA",
            "TronB",
            "TronC",
            "TronD",
            "LobsterA",
            "LobsterB",
            "LobsterC",
            "LobsterD",
            "FireBirdA",
            "FireBirdB",
            "FireBirdC",
            "SerpentA",
            "SerpentB",
            "SerpentC",
            "CloudA",
            "CloudB",
            "CloudC",
            "EmeraldA",
            "EmeraldB",
            "EmeraldC",
            "Crystalmon",
            "ElecDragon",
            "CrabA",
            "CrabB",
            "FireUmbrellaDragon",
            "Lanternmon",
            "SeedBugA",
            "SeedBugB",
            "SeedBugC",
            "NinjaBirdA",
            "NinjaBirdB",
            "NinjaBirdC",
            "NinjaBirdD",
            "NinjaCrowC",
            "NinjaCrowD",
            "MuffinTreeA",
            "MuffinTreeB",
            "MuffinTreeC",
            "SharkFishA",
            "SharkFishB",
            "SharkFishC",
            "FireGeckoA",
            "FireGeckoB",
            "EarthDino",
            "SlimeA",
            "SlimeB",
            "SlimeC",
            "SlimeD",
            "SeahorseA",
            "SeahorseB",
            "SeahorseC",
            "SeahorseD",
            "FireChickenA",
            "FireChickenB",
            "MAX",
            "START_MEGABOT",
            "Alpha",
            "Beta",
            "Gamma",
            "Ronin",
            "Bumblebee",
            "Orca",
            "Garuda",
            "Viper",
            "Blitz",
            "Cylops",
            "Kabuto",
            "Minotaur",
            "Spectre",
            "Wolf",
            "Bolt",
            "Hawk",
            "Cyber",
            "Space",
            "Hangar",
            "Arena",
            "UndergroundDark",
            "UndergroundLight",
            "RoninBoss",
            "OrcaBoss",
            "GarudaBoss",
            "ViperBoss",
            "Max",
            "Shockwave",
            "Tremor",
            "Rhino",
            "RoninArt",
            "GarudaArt",
            "MaxArt",
            "MinotaurArt",
            "WolfArt",
            "SkullArt",
            "OrcaAlt",
            "GarudaAlt",
            "ViperAlt",
            "KabutoAlt",
            "Neon",
            "Pulse",
            "Raptor",
            "AncientHammer",
            "ArcMissile",
            "Axe",
            "BarrageMissle",
            "BarrelHammer",
            "BattleChip",
            "BoxingGlove",
            "ChainGun",
            "ChillMissile",
            "ColdShoulder",
            "CrescentClaw",
            "CrescentMachete",
            "CrimsonWheel",
            "CryoBlaster",
            "Drill",
            "DualMissile",
            "ElecBroadsword",
            "ElectricChainsaw",
            "ElectricSpike",
            "EnergyShield",
            "FanBlade",
            "FeatherBlade",
            "FireAxe",
            "FireBroadsword",
            "FireKatana",
            "FireRocket",
            "FireShield",
            "FireTwinAxe",
            "Flamethrower",
            "FreezeBomb",
            "GigaBlade",
            "GigaCannon",
            "GreatCleaver",
            "HeatKnife",
            "HeatMissile",
            "IceBroadsword",
            "IceMortar",
            "IcePike",
            "IceSpinner",
            "IceTwinSpear",
            "InfernoBoost",
            "IronBall",
            "JetBurner",
            "Katana",
            "KnightShield",
            "KnightSword",
            "LightSaber",
            "LionShield",
            "MagneticCoil",
            "MaulerMace",
            "MegavoltBeam",
            "MiniMissile",
            "MissileCannon",
            "MoonlightBlade",
            "MorningStar",
            "Mortar",
            "PulseCannon",
            "RailCannon",
            "Ravager",
            "RocketMissile",
            "RollerSpike",
            "ShurikenBlade",
            "SonicBlaster",
            "SpikeBall",
            "SpikedWarhammer",
            "Sword",
            "ThorHammer",
            "Thunderblade",
            "ThunderTwinBlade",
            "WingBooster",
            "MAX_MEGABOT",
            "START_FANTASYRPG",
            "Archer",
            "ArmoredSlime",
            "AxeWarrior",
            "Basilisk",
            "Blacksmith",
            "CatMage",
            "CatPirate1",
            "CatThief",
            "Cook",
            "DarkKnight",
            "Dragon",
            "DragonKnight",
            "EldritchCreature",
            "Farmer",
            "Fencer",
            "Florist",
            "GoblinMage",
            "GoblinThief",
            "GoblinWarrior",
            "Golem",
            "Grandma",
            "Harpy1",
            "Harpy2",
            "InkKnight",
            "Jester1",
            "Jester2",
            "King",
            "Knight",
            "Lamia",
            "Mage",
            "Mimic1",
            "Mimic2",
            "MushroomMonster",
            "Noble1",
            "Noble2",
            "Peasant1",
            "Peasant2",
            "Phoenix",
            "Queen",
            "Reaper",
            "Schoolboy1",
            "SchoolBoy2",
            "Slime",
            "Snake",
            "Traveller",
            "TreeMonster",
            "Vampire",
            "Witch",
            "Wizard",
            "WolfFantasy",
            "MAX_FANTASYRPG",
            "START_CATJOB",
            "EX0Teacher",
            "EX0Detective",
            "EX0Woodworker",
            "EX0Plumber",
            "EX0Electrician",
            "EX0Soldier",
            "EX0General",
            "EX0Police",
            "EX0Fireman",
            "EX0Farmer",
            "EX0Architect",
            "EX0Construction",
            "EX0Bodybuilder",
            "EX0Archer",
            "EX0Explorer",
            "EX0Hiker",
            "EX0Programmer",
            "EX0Librarian",
            "EX0Laundry",
            "EX0Racer",
            "EX0Florist",
            "EX0Geologist",
            "EX0Gamer",
            "EX0Maid",
            "EX0Barber",
            "EX0Bartender",
            "EX0Bouncer",
            "EX0Composer",
            "EX0Director",
            "EX0Investor",
            "EX0Singer",
            "EX0Musician",
            "EX0Artist",
            "EX0Photographer",
            "EX0Lawyer",
            "EX0Janitor",
            "EX0Psychic",
            "EX0Astronaut",
            "EX0Scout",
            "EX0Pirate",
            "MAX_CATJOB"
        };
        // New Enums Dict
        public static Dictionary<string, int> TetramonEnums = new Dictionary<string, int> {
            {"Pigni", 1},
            {"Burpig", 2},
            {"Inferhog", 3},
            {"Blazoar", 4},
            {"Kidsune", 5},
            {"Bonfiox", 6},
            {"Honobi", 7},
            {"Kyuenbi", 8},
            {"Nanomite", 9},
            {"Decimite", 10},
            {"Meganite", 11},
            {"Giganite", 12},
            {"Sapoling", 13},
            {"Forush", 14},
            {"Timbro", 15},
            {"Mammotree", 16},
            {"Minstar", 17},
            {"Trickstar", 18},
            {"Princestar", 19},
            {"Kingstar", 20},
            {"Shellow", 21},
            {"Clamigo", 22},
            {"Aquariff", 23},
            {"Fistronk", 24},
            {"Wurmgle", 25},
            {"Pupazz", 26},
            {"Mothini", 27},
            {"Royalama", 28},
            {"Nocti", 29},
            {"Lunight", 30},
            {"Vampicant", 31},
            {"Dracunix", 32},
            {"Minotos", 33},
            {"Drilceros", 34},
            {"Grizzaw", 35},
            {"Jelicleen", 36},
            {"Wispo", 37},
            {"Mummog", 38},
            {"Helio", 39},
            {"Pixy", 40},
            {"Flory", 41},
            {"Magnoria", 42},
            {"Werboo", 43},
            {"Flami", 44},
            {"Angez", 45},
            {"Moskit", 46},
            {"Kyrone", 47},
            {"Twofrost", 48},
            {"Threeze", 49},
            {"Hydroid", 50},
            {"Drakon", 51},
            {"Bogon", 52},
            {"Hydron", 53},
            {"Raizon", 54},
            {"Tortugor", 55},
            {"Lupup", 56},
            {"Luphire", 57},
            {"Lucinder", 58},
            {"Lucadence", 59},
            {"Gupi", 60},
            {"Sharfin", 61},
            {"Gilgabass", 62},
            {"Jigajawr", 63},
            {"Batrang", 64},
            {"Dusko", 65},
            {"Wolgin", 66},
            {"Jacktern", 67},
            {"Tetron", 68},
            {"Raxx", 69},
            {"Gannon", 70},
            {"GigatronX", 71},
            {"Clawop", 72},
            {"Clawdos", 73},
            {"Clawaken", 74},
            {"Clawcifear", 75},
            {"Sunflork", 76},
            {"Scarlios", 77},
            {"Scarkgorus", 78},
            {"Crobib", 79},
            {"Crosilisk", 80},
            {"Crorathian", 81},
            {"Nimblis", 82},
            {"Nimboculo", 83},
            {"Nimbustrike", 84},
            {"Esmeri", 85},
            {"Esmerock", 86},
            {"Esmerdios", 87},
            {"Litspire", 88},
            {"Voltrex", 89},
            {"Crablox", 90},
            {"Clawvenger", 91},
            {"Flambrolly", 92},
            {"Lumie", 93},
            {"Seedant", 94},
            {"Budwing", 95},
            {"Buzzeed", 96},
            {"Beakai", 97},
            {"Talontsu", 98},
            {"Talonika", 99},
            {"Talonryu", 100},
            {"Kataryu", 101},
            {"Katengu", 102},
            {"Mufflin", 103},
            {"Muffleur", 104},
            {"Mufflimax", 105},
            {"Anguifish", 106},
            {"Amneshark", 107},
            {"Amnesilla", 108},
            {"Frizard", 109},
            {"Gekoflare", 110},
            {"Terradrakon", 111},
            {"Flamchik", 112},
            {"Pyropeck", 113},
            {"Poseia", 114},
            {"Posteed", 115},
            {"Poseigon", 116},
            {"Poseidrake", 117},
            {"Sludglop", 118},
            {"Sludgetox", 119},
            {"Toxigoop", 120},
            {"Toximuck", 121}
        };

        public static Dictionary<string, int> MegabotEnums = new Dictionary<string, int>
        {
            {"Alpha", 1},
            {"Beta", 2},
            {"Gamma", 3},
            {"Ronin", 4},
            {"Bumblebee", 5},
            {"Orca", 6},
            {"Garuda", 7},
            {"Viper", 8},
            {"Blitz", 9},
            {"Cyclops", 10},
            {"Kabuto", 11},
            {"Minotaur", 12},
            {"Spectre", 13},
            {"Wolf", 14},
            {"Bolt", 15},
            {"Hawk", 16},
            {"Cyber", 17},
            {"Space", 18},
            {"Hanger", 19},
            {"Arena", 20},
            {"UndergroundDark", 21},
            {"UndergroundLight", 22},
            {"RoninBoss", 23},
            {"OrcaBoss", 24},
            {"GarudaBoss", 25},
            {"ViperBoss", 26},
            {"Max", 27},
            {"Shockwave", 28},
            {"Tremor", 29},
            {"Rhino", 30},
            {"RoninArt", 31},
            {"GarudaArt", 32},
            {"MaxArt", 33},
            {"MinotaurArt", 34},
            {"WolfArt", 35},
            {"SkullArt", 36},
            {"OrcaAlt", 37},
            {"GarudaAlt", 38},
            {"ViperAlt", 39},
            {"KabutoAlt", 40},
            {"Neon", 41},
            {"Pulse", 42},
            {"Raptor", 43},
            {"AncientHammer", 44},
            {"ArcMissile", 45},
            {"Axe", 46},
            {"BarrageMisile", 47},
            {"BarrelHammer", 48},
            {"BattleChip", 49},
            {"BoxingGlove", 50},
            {"ChainGun", 51},
            {"ChillMissile", 52},
            {"ColdShoulder", 53},
            {"CresentClaw", 54},
            {"CresentMachete", 55},
            {"CrimsonWheel", 56},
            {"CryoBlaster", 57},
            {"Drill", 58},
            {"DualMissile", 59},
            {"ElectricBroadSword", 60},
            {"ElectricChainsaw", 61},
            {"ElectricSpike", 62},
            {"EnergyShield", 63},
            {"FanBlade", 64},
            {"FeatherBlade", 65},
            {"FireAxe", 66},
            {"FireBroadsword", 67},
            {"FireKatana", 68},
            {"FireRocket", 69},
            {"FireShield", 70},
            {"FireTwinAxe", 71},
            {"Flamethrower", 72},
            {"FreezeBomb", 73},
            {"GigaBlade", 74},
            {"GigaCommon", 75},
            {"GreatCleaver", 76},
            {"HeatKnife", 77},
            {"HeatMissile", 78},
            {"IceBroadsword", 79},
            {"IceMortar", 80},
            {"IcePike", 81},
            {"IceSpinner", 82},
            {"IceTwinSpear", 83},
            {"InfernoBoost", 84},
            {"IronBall", 85},
            {"JetBurner", 86},
            {"Katana", 87},
            {"KnightShield", 88},
            {"KnightSword", 89},
            {"LightSaber", 90},
            {"LionShield", 91},
            {"MagneticCoil", 92},
            {"MaulerMace", 93},
            {"MegaVoltBeam", 94},
            {"MiniMissile", 95},
            {"MissileCannon", 96},
            {"MoonlightBlade", 97},
            {"MorningStar", 98},
            {"Mortar", 99},
            {"PulseCannon", 100},
            {"RailCannon", 101},
            {"Ravager", 102},
            {"RocketMissile", 103},
            {"RollerSpike", 104},
            {"ShurikenBlade", 105},
            {"SonicBlaster", 106},
            {"SpikeBall", 107},
            {"SpikedWarhammer", 108},
            {"Sword", 109},
            {"ThorHammer", 110},
            {"Thunderblade", 111},
            {"ThunderTwinBlade", 112},
            {"Windblaster", 113}
        };

        public static Dictionary<string, int> FantasyRPGEnums = new Dictionary<string, int>
        {
            {"Archer", 1},
            {"ArmoredSlime", 2},
            {"AxeWarrior", 3},
            {"Basilisk", 4},
            {"Blacksmith", 5},
            {"CatMage", 6},
            {"CatPirate", 7},
            {"CatTheif", 8},
            {"Cook", 9},
            {"DarkKnight", 10},
            {"Dragon", 11},
            {"DragonKnight", 12},
            {"EldritchCreature", 13},
            {"Farmer", 14},
            {"Fencer", 15},
            {"Florist", 16},
            {"GoblinMage", 17},
            {"GoblinTheif", 18},
            {"GoblinWarrior", 19},
            {"Golem", 20},
            {"Grandma", 21},
            {"Harpy1", 22},
            {"Harpy2", 23},
            {"InkKnight", 24},
            {"Jester1", 25},
            {"Jester2", 26},
            {"King", 27},
            {"Knight", 28},
            {"Lamia", 29},
            {"Mage", 30},
            {"Mimic1", 31},
            {"Mimic2", 32},
            {"MushroomMonster", 33},
            {"Noble1", 34},
            {"Noble2", 35},
            {"Peasent1", 36},
            {"Peasent2", 37},
            {"Pheonix", 38},
            {"Queen", 39},
            {"Reaper", 40},
            {"Schoolboy1", 41},
            {"Schoolboy2", 42},
            {"Slime", 43},
            {"Snake", 44},
            {"Traveler", 45},
            {"TreeMonster", 46},
            {"Vampire", 47},
            {"Witch", 48},
            {"Wizard", 49},
            {"Wolf", 50}
        };

        public static Dictionary<string, int> CatJobEnums = new Dictionary<string, int>
        {
            {"Teacher", 1},
            {"Detective", 2},
            {"Woodworker", 3},
            {"Plumber", 4},
            {"Electrician", 5},
            {"Soldier", 6},
            {"General", 7},
            {"Police", 8},
            {"Firemen", 9},
            {"Farmer", 10},
            {"Architect", 11},
            {"Construction", 12},
            {"BodyBuilder", 13},
            {"Archer", 14},
            {"Explorer", 15},
            {"Hiker", 16},
            {"Programmer", 17},
            {"Laundry", 18},
            {"Libarian", 19},
            {"Racer", 20},
            {"Florist", 21},
            {"Geologist", 22},
            {"Gamer", 23},
            {"Maid", 24},
            {"Barber", 25},
            {"Bartender", 26},
            {"Bouncer", 27},
            {"Composer", 28},
            {"Director", 29},
            {"Investor", 30},
            {"Singer", 31},
            {"Musician", 32},
            {"Artist", 33},
            {"Photographer", 34},
            {"Janitor", 35},
            {"Lawyer", 36},
            {"Phychic", 37},
            {"Astronaut", 38},
            {"Pirate", 39},
            {"Scout", 40}
        };

        public static Dictionary<string, Dictionary<string, int>> SetDict = new Dictionary<string, Dictionary<string,int>>
        {
            {"Tetramon", TetramonEnums},
            {"Megabot", MegabotEnums},
            {"FantasyRPG", FantasyRPGEnums},
            {"CatJob", CatJobEnums}
        };

        public static List<string> Roles = new List<string>
        {
            "PhysicalAttacker",
            "Defender",
            "Support",
            "Healer",
            "MagicalAttacker",
            "AllRounder",
            "Disruptor"
        };
        public static List<string> Skills = new List<string>
        {
            "DoNothing",
            "Charging",
            "None",
            "FireClaw",
            "BlazingClaw",
            "InfernoClaw",
            "HellfireClaw",
            "FlamePillar",
            "BlazingPillar",
            "InfernoPillar",
            "SunPillar",
            "SpitFire",
            "Fireball",
            "MegaFlare",
            "CometStrike",
            "PiercingHit",
            "PiercingStrike",
            "PiercingCrash",
            "OmegaPierce",
            "BlitzAttack",
            "BlitzStrike",
            "BlitzSmash",
            "BlitzCrash",
            "FireWall",
            "InfernoWall",
            "BlazingWall",
            "HellfireWall",
            "PsychUp",
            "CriticalWound",
            "DesperadoHit",
            "SolarFlare",
            "Counter",
            "FrenzyHit",
            "Charge",
            "SuperCharge",
            "MegaCharge",
            "GigaCharge",
            "StoneWall",
            "RockWall",
            "GiantWall",
            "GigaWall",
            "Grow",
            "SuperGrow",
            "MegaGrow",
            "GigaGrow",
            "PebbleBlast",
            "StoneBlast",
            "RockSmash",
            "BoulderCrush",
            "Cover",
            "Protection",
            "Safeguard",
            "PerfectGuard",
            "HardenShell",
            "FortifyShell",
            "PowerUp",
            "Sharpen",
            "FuryStrike",
            "SwipeAttack",
            "Earthquake",
            "AncientProtection",
            "HealingMist",
            "HealingShower",
            "HealingRain",
            "HealingWaterfall",
            "EnergyPool",
            "EnergyFountain",
            "EnergyRain",
            "EnergyFlood",
            "DrainHit",
            "DrainStrike",
            "DrainSmash",
            "DrainCrush",
            "ColdShot",
            "IceBurst",
            "IcicleBlast",
            "SubzeroBeam",
            "RegenPool",
            "RegenFountain",
            "RegenRain",
            "RegenFlood",
            "Osmosis",
            "CleansingMist",
            "IcicleField",
            "MassAbsorb",
            "Consume",
            "Rejuvenate",
            "PoisonFang",
            "VenomFang",
            "ToxicFang",
            "AcidFang",
            "PoisonBlast",
            "VenomBlast",
            "ToxicBlast",
            "AcidBlast",
            "SandShot",
            "SandBlast",
            "SandStorm",
            "SandHurricane",
            "PowerDrip",
            "PowerLeak",
            "Discharge",
            "Meltdown",
            "AirShot",
            "AirCutter",
            "SonicBoom",
            "WindBlade",
            "Berserk",
            "FocusFire",
            "PoisonMist",
            "PoisonStorm",
            "BlindingSmog",
            "StickyGoo",
            "SpeedUp",
            "SpeedDown",
            "SleepShot",
            "SleepBlast",
            "SleepMist",
            "SleepStorm",
            "Tornado",
            "MassBerserk",
            "Tailwind",
            "BattleCry",
            "None",
            "ThunderClaw",
            "StormClaw",
            "LightningClaw",
            "TempestClaw",
            "ThunderPillar",
            "StormPillar",
            "LightningPillar",
            "TempestPillar",
            "ElectricShock",
            "LightningBolt",
            "ThunderStrike",
            "StormStrike",
            "TempestStrike",
            "ShockingHit",
            "BlindingFlash",
            "Frostbite",
            "IcicleSlash",
            "GlacialBlow",
            "ArcticBlast",
            "Hailstorm",
            "IceStorm",
            "SnowballFight",
            "FrostField",
            "BlizzardBlast",
            "DrenchingRain",
            "FloodSurge",
            "TidalWave",
            "SurgingTide",
            "WaveCrash",
            "TorrentStrike",
            "GaleForce",
            "Windstorm",
            "Cyclone",
            "Whirlwind",
            "Vortex",
            "Hurricane",
            "Twister",
            "SpinAttack",
            "ChargeAttack",
            "CounterStrike",
            "ReboundHit",
            "Shockwave",
            "PulseWave",
            "ForceField",
            "Barrier",
            "ShieldBash",
            "ReflectHit",
            "EnergyGuard",
            "AuraShield",
            "SpiritWall",
            "MysticVeil"
        };

        // Add Ability to add new Rarities later.
    }
}